[package]
name = "multirun"
version = "0.1.0"
authors = ["Nico Burns <nico@nicoburns.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.2", features = ["full"] }
futures = "0.3.1"
futures-util = "0.3.1"
